---
# tasks file for mapr_cluster_startup

- name: start the warden on all nodes
  sudo: yes
  sudo_user: root
  service: name={{item}} state=started
  with_items:
    - mapr-warden

- name: wait for the fileserver to be listening
  wait_for: port=5660
