---
# tasks file for mapr_cluster_startup

- name: start the warden on all nodes
  become: yes
  become_user: root
  service: name={{item}} state=started
  with_items:
    - mapr-warden

- name: is fuse client mounted?
  shell: mount | grep posix-client-basic
  register: mount
  failed_when: mount.rc not in (0,1)

# Using restarted to work around defect 23021
- name: start posix client on all nodes
  become: yes
  become_user: root
  service: name=mapr-posix-client-{{posix_client_edition|default("basic")}} state=restarted
  when: posix_client_enabled is defined and posix_client_enabled == True and mount.rc == 1

- name: wait for the fileserver to be listening
  wait_for: port=5660
